- name: Run script
      env:
        EU_USERNAME: ${{ secrets.EU_USERNAME }}
        EU_PASSWORD: ${{ secrets.EU_PASSWORD }}
        EU_2FA_SECRET: ${{ secrets.EU_2FA_SECRET }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      run: python Github_Action.py
