name: Auto EUserv

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: # 这个一定要有，才会显示 Run workflow 按钮

jobs:
  run-renewal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Renewal Script
        env:
          EU_USERNAME: ${{ secrets.EU_USERNAME }}
          EU_PASSWORD: ${{ secrets.EU_PASSWORD }}
          EU_2FA_SECRET: ${{ secrets.EU_2FA_SECRET }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python Github_Action.py
